### PR TITLE
character warning limit (ready for testing)

### LINKED ISSUE #101: [Suggestion] Warning when deploying code that goes over SE's character limit
Basically what the title says, give a warning/error if code goes over keens set 100k character limit when trying to deploy.

### PR DESCRIPTION
**Pull request by SCBionicle**
Fixes #101

An implementation of the character limit warning. I'm unfamiliar with visual studio extension API, especially when it comes to the error list window. I got a borked installation which is preventing me from compiling, if someone else could if this works, not asking for debugging, though, if you don't want to.

### CODE REVIEW

**Comment by SCBionicle** [comment]
If anyone's wondering, I was was using this as reference, but it provides an incomplete picture.

https://gist.github.com/DinisCruz/3185313

**Comment by SCBionicle** [comment]
If I may ask, why was this closed?

**Comment by malware-dev** [comment]
Well, ignoring the fact that it as a completely untested thing by your own admission... the more important thing is #308.

MDK1 is for all intents and purposes dead. MDK2 is underway.

**Comment by SCBionicle** [comment]
I understand. Sucks that Microsoft broke your functionality. I might have a few private projects I could share with you to help develop the minifier. 

P.S. It's been a while since I work on this, but I could have sworn I tested it and was waiting for approval. Oh well.

**Pull request closed without merging**
