### PR TITLE
Added support for Environment Variables in the script output directory to fix #89.

### LINKED ISSUE #89: MDK.options causes Access Denied errors during deployment.
Reproduction:
1. Create a project which deploys correctly on one user account.
2. Open the same project on a different user account.
3. Attempt to deploy the MDK script.

Expected Behaviour:
Project deploys to the AppData\Roaming\SpaceEngineers\IngameScripts\local folder of the currently active account.

Actual:
The script deployment fails with an Access Denied error.

Cause:
MDK.options parser doesn't correctly expand environment variables like %APPDATA%, all paths are hard-coded.
This means attempting to run a project on a computer/user account where the AppData folder isn't under the same user directory as the original author will cause an Access Denied error during deployment.

### PR DESCRIPTION
**Pull request by kwilliams1987**
Adds the %APPDATA% environment variable to your ExpandMacros subroutine during project builds.

### CODE REVIEW

**Comment by malware-dev** [comment]
Well would you look at that; an honest to gosh pull request! Most obliged my friend, I will review as soon as I can.

**Comment by kwilliams1987** [comment]
Visual Studio addons are not my forte, but this one seemed fairly trivial to implement.

Hope I'm not embarrassing myself. 👍

**Comment by malware-dev** [comment]
I am _so_ sorry, but I cannot accept this pull request. If environment variables are to be supported, _all of them_ must be supported, using `Environment.ExpandEnvironmentVariables`.

**Comment by kwilliams1987** [comment]
I had read that the Environment.ExpandEnvironmentVariables could be quite unreliable.

I will update it to match that requirement though. 👍

**Comment by kwilliams1987** [comment]
Exactly none of my code was in the final pull request, but I felt like I helped!

**Comment by malware-dev** [comment]
Oh you _absolutely_ helped! And I'm very grateful for it. This is still technically your code, I just optimized it _and_ my own code a little ;)

**Pull request merged**
